# MPSSE shift command flags (OR mask)
WRITE_NEG  = 0x01
BITS       = 0x02
READ_NEG   = 0x04
LSB        = 0x08
WRITE      = 0x10
READ       = 0x20
TMS        = 0x40
MANAGEMENT = 0x80

# Management commands
SET_BITS_LOW         = MANAGEMENT | 0x00
GET_BITS_LOW         = MANAGEMENT | 0x01
SET_BITS_HIGH        = MANAGEMENT | 0x02
GET_BITS_HIGH        = MANAGEMENT | 0x03
LOOPBACK_ENABLE      = MANAGEMENT | 0x04
LOOPBACK_DISABLE     = MANAGEMENT | 0x05
CLK_DIV              = MANAGEMENT | 0x06
SEND_IMMEDIATE       = MANAGEMENT | 0x07
WAIT_ON_HIGH         = MANAGEMENT | 0x08
WAIT_ON_LOW          = MANAGEMENT | 0x09
CLK_DIV5_DISABLE     = MANAGEMENT | 0x0a
CLK_DIV5_ENABLE      = MANAGEMENT | 0x0b
THREE_PHASE_ENABLE   = MANAGEMENT | 0x0c
THREE_PHASE_DISABLE  = MANAGEMENT | 0x0d
CLK_BITS             = MANAGEMENT | 0x0e
CLK_BYTES            = MANAGEMENT | 0x0f
CLK_WAIT_HIGH        = MANAGEMENT | 0x14
CLK_WAIT_LOW         = MANAGEMENT | 0x15
ADAPTIVE_ENABLE      = MANAGEMENT | 0x16
ADAPTIVE_DISABLE     = MANAGEMENT | 0x17
CLK_BYTES_OR_HIGH    = MANAGEMENT | 0x1c
CLK_BYTES_OR_LOW     = MANAGEMENT | 0x1d
DRIVE_OPEN_COLLECTOR = MANAGEMENT | 0x1e
